services:
  app:
    build: ./backend/
    volumes:
      - ./backend:/go/src/app
      - ./schema:/go/src/schema
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_USER: habook
      DB_PASSWORD: habook
      DB_HOST: db
    tty: true
    stdin_open: true
  db:
    image: mysql:8.2
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: habook
      MYSQL_USER: habook
      MYSQL_PASSWORD: habook
      MYSQL_DATABASE: habook
      TZ: "Asia/Tokyo"
    volumes:
      - mysql-db:/var/lib/mysql

volumes:
  mysql-db:
    driver: local
