version: '3'
services:
  mysql:
    image: mysql:8.0
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: habook
      MYSQL_USER: habook
      MYSQL_PASSWORD: habook
      MYSQL_DATABASE: habook
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql-db:/var/lib/mysql

volumes:
  mysql-db:
    driver: local
