// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ExpenseHistory struct {
	ID        string `json:"id"`
	Expense   int    `json:"expense"`
	User      *User  `json:"user"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

type NewCategory struct {
	Name   string `json:"name"`
	UserID string `json:"userId"`
}

type NewExpenseHistory struct {
	Expense int    `json:"expense"`
	UserID  string `json:"userId"`
}

type NewUser struct {
	Name string `json:"name"`
}

type User struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Enable    bool   `json:"enable"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}
