// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ExpenseHistory struct {
	Pk        int    `json:"pk"`
	ID        string `json:"id"`
	Expense   int    `json:"expense"`
	User      *User  `json:"user"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

type NewExpenseHistory struct {
	Expense int    `json:"expense"`
	UserID  string `json:"userId"`
}
