name: ESLint Frontend

on:
  pull_request:
    paths:
      - 'frontend/**'
    types: [ opened, synchronize ]
jobs:
  eslint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './frontend'
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install dependencies
        run: yarn install
      - name: ESLint
        uses: reviewdog/action-eslint@v1
        with:
          workdir: './frontend/'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          eslint_flags: './**/*.{ts,tsx}'
      - name: yarn lint
        run: yarn lint
