name: Build Next.js

on:
  pull_request:
    paths:
      - 'frontend/**'
    types: [ opened, synchronize ]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './frontend'
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.13.2'
      - name: Install dependencies
        run: yarn install
      - name: build
        run: yarn build
